runtime: python27
api_version: 1
threadsafe: false

network:
  session_affinity: false

libraries:
- name: django
  version: "1.2"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /photo
  script: photo.py

- url: /audio
  script: audio.py

- url: /spot
  script: spotlight.py

- url: /puzzle
  script: puzzle.py

- url: /.html
  static_files: /\1
  upload: /.html
  mime_type: text/html; charset=UTF-8

- url: /photo2.html
  static_files: photo2.html
  upload: photo2.html

- url: /htmlSizeChecker.html
  static_files: htmlSizeChecker.html
  upload: htmlSizeChecker.html

- url: /cookingSearch.html
  static_files: cookingSearch.html
  upload: cookingSearch.html

- url: /cookingSearch.xml
  static_files: cookingSearch.xml
  upload: cookingSearch.xml

- url: /cookingSearch
  script: cookingSearch.py

- url: /drawing
  script: drawing.py

- url: /drawingPost
  script: drawing.py

- url: /readingOut
  script: readingOut.py

- url: /typing
  static_files: typing.html
  upload: typing.html

- url: /.*
  script: helloworld.py
