application: bluehatspractice
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /photo
  script: photo.py

- url: /.html
  static_files: /\1
  upload: /.html
  mime_type: text/html; charset=UTF-8
  
- url: /.*
  script: helloworld.py
